[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "nll"
version = "0.1.0"
dependencies = ["numpy", "matplotlib", "scipy"]

[tool.setuptools.packages.find]
include = ["nll"]
